### ISSUE TITLE
User build/run time configuration

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/willow#11]
We should have reasonable defaults for things like wake word engine, VAD aggressiveness, etc but at a minimum we should move them into the Kconfig/config system (under Willow Configuration).

When we have a Home Assistant component working we can specify the configuration there and have ESP Boxes push/pull the preferred configuration from our Home Assistant API endpoint as JSON to configure the ESP Boxes dynamically on startup or on demand.

**Comment by stintel** [comment]
https://github.com/toverainc/willow/releases/tag/0.1.0-rc.1
