### ISSUE TITLE
stuck on start up (server)

### ISSUE THREAD

**Issue by Chrusciki** [toverainc/willow#128]
on a ESP32-S3-Box-Lite the display shows "Starting up (server)..." and the terminal shows "Starting up! Please wait..."
nothing else has happened after flashing any ideas?

**Comment by kristiankielhofner** [comment]
Can you provide the full output from the serial monitor?

**Comment by Chrusciki** [comment]
Update: wifi password was incorrect. closing issue.

**Comment by kristiankielhofner** [comment]
Re-opening because we should show these kinds of errors on the LCD display so they're more explicit/obvious

**Comment by stintel** [comment]
I think we can close this after baf140e4c637a7d43f81089beec059c02b0a851f?
