### ISSUE TITLE
Implement stream/VAD timeout

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/willow#18]
I am still seeing cases where VAD/wake end never happens.

In testing I had a device stream continuously for 12 hours before I finally pulled the power...

It's very difficult to reproduce but:

1) It makes testing/development frustrating for me. I believe my issues are related to wifi environment but I have experienced this in multiple completely different environments - Wisconsin (two Unifi APs) and California (Qualcomm and Meditek AP). FWIR stintel has yet to observe this issue.

2) We don't (currently) have a use case where endless streaming makes sense anyway.

We should implement a timeout based on either seconds (10, maybe?), number of audio chunks, something to timeout streaming no matter what.

It seems that if I wait for a few seconds after the display indicates ready it's much less likely to occur.

**Comment by stintel** [comment]
I do sometimes press the cancel button because VAD/WAKE end don't trigger. This happens very often right after booting the device. This might be related to https://github.com/espressif/esp-sr/issues/47#issuecomment-1259365973:
>  Why we choose raw data for the first time is that the BSS algorithm need to take some time to converge.
