### ISSUE TITLE
Parameters for dynamic configuration

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/willow#193]
The dynamic configuration manifest should also include:

- Hardware device type (ESP BOX, ESP BOX Lite)
- A user label and/or description

**Comment by lordratner** [comment]
Static IP/Gateway/DNS options would be handy. I didn't see that in the current config.

**Comment by lordratner** [comment]
> Static IP/Gateway/DNS options would be handy. I didn't see that in the current config.

Nevermind, it looks like you already have it from the screenshot of WAS in another post. Cheers!

**Comment by kristiankielhofner** [comment]
Yes, but it doesn't support static IP. Binding a MAC address to a specific IP address will have to be done in your router/DHCP server for now.

**Comment by stintel** [comment]
Device type was added in c02b457d915d25da88773c7d2d6b2422d4c59d0d.

**Comment by stintel** [comment]
Once we merge https://github.com/toverainc/willow-application-server/pull/15 this can be closed.
