### ISSUE TITLE
Better config management

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/willow#21]
Instead of depending on using one gigantic sdkconfig.willow we should probably have at least three:

- Defaults for everything (from espressif)
- Overrides for Willow configs
- Use overrides for things like the Willow Configuration options

**Comment by mineshaftgap** [comment]
Curious why not a web UI configuration like other ESP8266/32 projects where you connect to an open WiFi network to enter actual WiFi details and then after that you can change all the other configuration. With this approach a firmware can be distributed for those who are much less technically inclined.

**Comment by kristiankielhofner** [comment]
This issue is intended to track the configuration of the build system. No matter where a firmware image comes from, or how it's configured by the end user, it needs to be built by a build system somewhere.

We are evaluating a variety of approaches for easier end-user onboarding and configuration such as those [mentioned on the wiki](https://github.com/toverainc/willow/wiki/Home-Assistant#the-future).

We have a larger issue than a firmware image and checksum. All a checksum assures is that it wasn't modified from the time we built and when the checksum was generated. It in no way assures the user that we didn't modify the code to stream their audio to some server we host (or who knows what), build it, generate a checksum, and hand them a binary.

The ideal approach is to use reproducible builds which we are also investigating given our focus on user privacy as a voice assistant.

We take our responsibility of powering a device with microphones present in the private lives of our users very, very seriously. We understand our primary differentiator is the trust of our users. For issues such as these we are going to approach them very methodically, deliberately, and with the involvement and feedback of the community and user base.

**Comment by mineshaftgap** [comment]
Oh apologies, I didn't realize the intention for this.

**Comment by stintel** [comment]
https://github.com/toverainc/willow/tree/feature/sdkconfig_defaults
