### ISSUE TITLE
Investigate display timeout variability

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/willow#23]
The display timeout isn't completely reliable.

The timers in ESP-IDF are being re-worked - save this for that.

**Comment by stintel** [comment]
Should be improved by fed9875488e7a39481a043a3c1642fb1f9aeb7d6. Still not perfect though.

**Comment by stintel** [comment]
Maybe we can close this after ce2749abe49fa64bd255a916d89fd95876c46fe8?
