### ISSUE TITLE
exported PORT is not supplied to docker container?

### ISSUE THREAD

**Issue by richardklafter** [toverainc/willow#24]
Ran `export PORT=/dev/ttyACM0` as documented but that is not passed into docker container as an `ENV` var or passed to `--device` ?

**Comment by Xlinx64** [comment]
I still have this issue. I see it on my mac when i use `ls /dev/cu.*`. But after I set it and want to flash it I get this error:
`A fatal error occurred: Could not open /dev/cu.usbmodem14201, the port doesn't exist`
Do I have to change something?

**Comment by Xlinx64** [comment]
Ah, thank you.
I didnt get that I had to flash from outside the container.
Unfortunately flashing doesnt work. `esptool: error: argument --chip/-c: invalid choice: 'esp32s3' (choose from 'auto', 'esp8266', 'esp32')`
But I think this is out of scope of this issue.

**Comment by kristiankielhofner** [comment]
I will make the documentation and error messages clearer. If you'd like to make a new issue for your new error we can work it there, or I can offer the quick (potential) fix of:

On the host:
```
rm -rf venv
./utils.sh flash
```

**Comment by kristiankielhofner** [comment]
Appreciate your patience on this! If you could make a new issue please we can work through this there.

Thank you so much!
