### ISSUE TITLE
Product Discontinued: ESP32-S3 Box

### ISSUE THREAD

**Issue by profucius** [toverainc/willow#370]
Opening a ticket here to raise awareness and seek advice on the future of this project.

Adafruit has announced immediate discontinuation of the [ESP32-S3 Box](http://www.adafruit.com/products/5290) product line. This includes the Lite version as well.

I own three of these devices currently, and they work with the current builds of Willow. However I am concerned that the Willow project seemed to depend on these devices, and I'd like to ask if you have plans to shift to another device, or another voice detection method in the future?

My two cents would be to more-tightly integrate with Home Assistant, and use their Voice Assistant feature to trigger the Willow backend. Or some method such as this.

I hope this project continues to live, as it has a lot of promise going forward!

**Comment by nikito** [comment]
I think both of those devices were prototypes, and discontinued in favor of the ESP32-S3-Box-3, which I don't believe is discontinued.

**Comment by profucius** [comment]
I didn't realize there was yet another variant (-3) on the market. That certainly eliminates the alarm. I'm still concerned however that the new variant is also Out of Stock, as the previous ones were too. I wonder if there is any point in asking if there are any backup plans, in case they rarely or never return to stock? I only don't want to see this project fade away because the hardware is difficult to obtain.

**Comment by nikito** [comment]
Espressif has said they are ramping up production, and sites like mouser show more units on the way. Also, HA also uses this same hardware for voice assistant satellites; tech like microWakeWord use the Box-3 🙂. We also have users in the community working on their own open source hardware based on the ESP32-S3 chip, and willow really can support anything that is supported by the ESP-IDF framework with some firmware tweaks, so don't think there is any reason to be alarmed 🙂

**Comment by profucius** [comment]
Glad to hear it, thanks for assuaging my concerns then! I'll close this ticket out.
