### ISSUE TITLE
`./utils.sh config` results in Failed to resolve component 'esp-adf-libs'.

### ISSUE THREAD

**Issue by mineshaftgap** [toverainc/willow#41]
When trying to build, running the step `./utils.sh config` produces:

...
```
[6/6] lvgl/lvgl (8.3.7)
CMake Error at /opt/esp/idf/tools/cmake/build.cmake:201 (message):
  Failed to resolve component 'esp-adf-libs'.
Call Stack (most recent call first):
  /opt/esp/idf/tools/cmake/build.cmake:236 (__build_resolve_and_add_req)
  /opt/esp/idf/tools/cmake/build.cmake:237 (__build_expand_requirements)
  /opt/esp/idf/tools/cmake/build.cmake:242 (__build_expand_requirements)
  /opt/esp/idf/tools/cmake/build.cmake:242 (__build_expand_requirements)
  /opt/esp/idf/tools/cmake/build.cmake:518 (__build_expand_requirements)
  /opt/esp/idf/tools/cmake/project.cmake:393 (idf_build_process)
  CMakeLists.txt:10 (project)


-- Configuring incomplete, errors occurred!
See also "/willow/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
```

**Comment by mineshaftgap** [comment]
Here is the log.
[CMakeOutput.log](https://github.com/toverainc/willow/files/11492188/CMakeOutput.log)

**Comment by kristiankielhofner** [comment]
Can you try `cd deps/esp-adf && git submodule update --init components/esp-adf-libs` ?

**Comment by mineshaftgap** [comment]
This seems to be currently working, but had to run `git config --global --add safe.directory /willow/deps/esp-adf` to make it work.

**Comment by mineshaftgap** [comment]
After it the above completes and I run `./utils.sh config` again it produces the same error. I am going to try dumping the running container and trying again with your `git submodule update`

**Comment by mineshaftgap** [comment]
Well looks like I keep getting the error, any other ideas?

**Comment by kristiankielhofner** [comment]
At this point I have no idea where your environment is so please run `./utils.sh destroy` and start from the top of install in the container.

**Comment by kristiankielhofner** [comment]
With that latest commit try re-building your container and try again

**Comment by mineshaftgap** [comment]
That did it, `./utils.sh config` completed.

**Comment by mineshaftgap** [comment]
Thanks so much!

**Comment by kristiankielhofner** [comment]
That was kind of an obvious one on our part. Glad we could work through it! Let us know if you have any other issues.
