### ISSUE TITLE
New Feature? countdown timer

### ISSUE THREAD

**Issue by mineshaftgap** [toverainc/willow#91]
One of the things I currently us a lot on Alexa is a countdown timer so in order to try replace it, I need that functionality. I wanted to see if there was interest in having this be part of the project? If so I can look to see what it would take to implement it.

**Comment by kristiankielhofner** [comment]
I haven't completely thought it through yet but I've started mentally modeling another architecture component - the Willow Application Server.

Willow devices would maintain a persistent websocket connection with eventing to WAS.

WAS would support official and community Willow Application repos and the processing for these applications and (far, far) beyond would take place there. Of course you'd also be able to create whatever applications you want. 

For a time you'd match the WAS timer app and it would event one or more Willow devices to play a configured chime, TTS output, whatever you want.
